version: "3.9"
services:
  # RabbitMQ service
  rabbitmq:
    image: rabbitmq:management # RabbitMQ with management plugin
    networks:
      - app-network
    ports:
      - "5672:5672" # RabbitMQ port
      - "15672:15672" # RabbitMQ management UI port

  # Redis service
  redis:
    image: redis:latest
    networks:
      - app-network
    ports:
      - "6379:6379" # Redis port

  # MySQL service
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: cron
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    networks:
      - app-network
    ports:
      - "3306:3306" # MySQL port
    restart: always
    expose:
      - "3306"

  # API service
  api:
    build: .
    ports:
      - "3000:3000" # Your API's port
    depends_on:
      - redis
      - rabbitmq
      - mysql
    networks:
      - app-network
    environment:
      # Add any environment variables your Node.js API requires
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
      MYSQL_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: cron

networks:
  app-network:
    driver: bridge
